### ISSUE TITLE
Link to Live Demo for input devices (LittlevGL 6.1.2) is broken

### ISSUE THREAD

**Issue by dhebbeker** [lvgl/docs#110]
In [this section](https://docs.lvgl.io/en/html/overview/indev.html#live-demo) the [link to the live demo](https://littlevgl.com/demo-touchpadless) is broken.

**Comment by embeddedt** [comment]
The 6.x live demos are no longer available on the site, so I've changed the link to point to that example's source code. You can run it on the PC simulator.

**Comment by dhebbeker** [comment]
Thanks!
