### ISSUE TITLE
lv_style_set_text_font documentation not updated

### ISSUE THREAD

**Issue by C47D** [lvgl/docs#115]
Documentation about [lv_style_set_text_font](https://docs.lvgl.io/v7/en/html/overview/font.html?highlight=lv_style_set_text_font) isn't updated, it needs three arguments instead of the documented two.

From 7.0.1 docs.

**Comment by embeddedt** [comment]
Thanks; I've fixed it here: https://github.com/lvgl/docs/commit/8d77752e04e63bd9697c171210f7d4a8a3fa7fa5
