### ISSUE TITLE
spinner or preload widget?

### ISSUE THREAD

**Issue by C47D** [lvgl/docs#116]
On the spinner [docs](https://docs.lvgl.io/v7/en/html/widgets/spinner.html) the example creates a spinner widget named `preload`, from that point forward most of the spinner related functions talks about a `preload` object but I think it refers to the spinner instead.

Or should the spinner widget be renamed to preload?

From:
> Functions
> 
> lv_obj_t *lv_spinner_create(lv_obj_t *par, const lv_obj_t *copy)
> 
>     Create a pre loader objects
> 
>     Return
> 
>         pointer to the created pre loader
>     Parameters
> 
>             par: pointer to an object, it will be the parent of the new pre loader
> 
>             copy: pointer to a pre loader object, if not NULL then the new object will be copied from it
> 
> void lv_spinner_set_arc_length(lv_obj_t *preload, lv_anim_value_t deg)
> 
>     Set the length of the spinning arc in degrees
> 
>     Parameters
> 
>             preload: pointer to a preload object
> 
>             deg: length of the arc

To:

> Functions
> 
> lv_obj_t *lv_spinner_create(lv_obj_t *par, const lv_obj_t *copy)
> 
>     Create a spinner object
> 
>     Return
> 
>         pointer to the created spinner
>     Parameters
> 
>             par: pointer to an object, it will be the parent of the new spinner
> 
>             copy: pointer to a spinner object, if not NULL then the new object will be copied from it
> 
> void lv_spinner_set_arc_length(lv_obj_t *spinner, lv_anim_value_t deg)
> 
>     Set the length of the spinning arc in degrees
> 
>     Parameters
> 
>             spinner: pointer to a spinner object
> 
>             deg: length of the arc

**Comment by embeddedt** [comment]
Spinner is the new name for the former "preload" object.

**Comment by C47D** [comment]
So it needs to be updated? If so I can send a PR, but I don't know if the LVGL code will also need to be updated.

**Comment by kisvegabor** [comment]
> So it needs to be updated?

Yes, it needs to be updated both in lvgl and the docs. Seemly I haven't replaced all occurrences.

**Comment by kisvegabor** [comment]
Sorry, I forget to answer here.

It seems the `preloader->spinner` thing is already solved.
