### ISSUE TITLE
Styles: minor issues

### ISSUE THREAD

**Issue by DaPa** [lvgl/docs#126]
Padding and margin properties: 
the properties (pad_top, pad_bottom, etc) are not bulleted.

Border properties:
The border in drawn on to of the background.  => The border **is** drawn on **top** of the background. _(please check if it's true)_

Border properties:
border_post (bool): If true the border will be drawn all children has been drawn. => If true the border will be drawn **when** all children **have** been drawn.

Shadow properties:
shadow_spread: ake => **make**

Value properties:
values_str: Only the pointer is saved. => Only the pointer is saved! Don't use local variable with lv_style_set_value_str, else use lv_obj_set_style_local_value_str.

Transition properties:
transition_1 to transition_6: an other =>  another
**Question**: should be transition_**prop**_1? Because the macros are called lv_style_set_transition_prop_1 ... 

_These are all findings plus the questions_

**Comment by DaPa** [comment]
**Question**: is this generally true that that lv_style_set_XXX can be replaced with lv_obj_set_style_local_XXX? Because at Transition properties, for transition_path there is similar pointer situation: "An animation path for the transition. (Needs to be static or global variable because only its pointer is saved)". Can there also be used lv_obj_set_style_local_transition_path?

Answering my question: seems it might be true that lv_style_set_XXX can be replaced with lv_obj_set_style_local_XXX. Tested with lv_ex_style_8 and these two gave equivalent results:

```
void lv_ex_style_8(void)
{
    static lv_style_t style;
    lv_style_init(&style);

    lv_style_set_line_color(&style, LV_STATE_DEFAULT, LV_COLOR_GRAY);
    lv_style_set_line_width(&style, LV_STATE_DEFAULT, 6);
    lv_style_set_line_rounded(&style, LV_STATE_DEFAULT, true);

    /*Create an object with the new style*/
    lv_obj_t * obj = lv_line_create(lv_scr_act(), NULL);
    lv_obj_add_style(obj, LV_LINE_PART_MAIN, &style);

    static lv_point_t p[] = {{10, 30}, {30, 50}, {100, 0}};
    lv_line_set_points(obj, p, 3);

    lv_obj_align(obj, NULL, LV_ALIGN_CENTER, 0, 0);
} 
```

```
void lv_ex_style_8(void)
{
    /*Create a line with given new style*/
    lv_obj_t * obj = lv_line_create(lv_scr_act(), NULL);
    lv_obj_set_style_local_line_color(obj, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, LV_COLOR_GRAY);
    lv_obj_set_style_local_line_width(obj, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, 6);
    lv_obj_set_style_local_line_rounded(obj, LV_OBJ_PART_MAIN, LV_STATE_DEFAULT, true);

    static lv_point_t p[] = {{10, 30}, {30, 50}, {100, 0}};
    lv_line_set_points(obj, p, 3);

    lv_obj_align(obj, NULL, LV_ALIGN_CENTER, 0, 0);
} 
```

**Comment by kisvegabor** [comment]
Hi,

Thank you for pointing these out.

Could you send a PR to be sure we don't miss anything?
You can use the "Edit on GitHub" button on the top of every page to easily find and edit the files.

**Comment by kisvegabor** [comment]
> Question: is this generally true that that lv_style_set_XXX can be replaced with lv_obj_set_style_local_XXX? Because at Transition properties, for transition_path there is similar pointer situation: "An animation path for the transition. (Needs to be static or global variable because only its pointer is saved)". Can there also be used lv_obj_set_style_local_transition_path?

Yes, they are equivalent. Every object has a "built-in" style (the local style) which can be accessed via the `lv_obj_set_style_local_...` finctions.

**Comment by DaPa** [comment]
Thanks for the answer, yes I'll try to make asap a PR.

**Comment by DaPa** [comment]
Oh! Not sure where I have to modify... Searching for "The border in drawn on to of the" I found it in these 6 files:
    \docs\dev\en\html\_sources\overview\style.md.txt
    \docs\dev\en\html\overview\style.html
    \docs\latest\en\html\_sources\overview\style.md.txt
    \docs\latest\en\html\overview\style.html
    \docs\v7\en\html\_sources\overview\style.md.txt
    \docs\v7\en\html\overview\style.html
Can you please point which? Should be in all? Or are some generated from others? Thank you!

**Comment by kisvegabor** [comment]
It should be modified here: https://github.com/lvgl/docs/blob/latest/overview/style.md

I wrote a short summary in the REDME about the branches of the docs and how to contribute.
https://github.com/lvgl/docs/tree/master

**Comment by DaPa** [comment]
Clear! Thank you! PR just made.
