### ISSUE TITLE
Charts: I need a clarification about styles

### ISSUE THREAD

**Issue by DaPa** [lvgl/docs#127]
The docs says: 
The Chart’s main part is called LV_CHART_PART_BG and it uses all the typical background properties. The text style properties determine the style of the axis texts and the line properties determine ticks’ style. Padding values add some space on the sides thus it makes series area smaller. Padding also can be used to make space for axis texts and ticks.
The background of the series is called LV_CHART_PART_SERIES_BG and it’s placed on the main background. The division lines, and series data is drawn on this part. Besides the typical background style properties the line style properties are used by the division lines. The padding values tells the space between the this part and the axis texts.

**Long question**: for the 3rd element (LV_CHART_PART_SERIES) it's easy to see what styles can be changed as they are clearly listed. But for above first 2 (LV_CHART_PART_BG and LV_CHART_PART_SERIES_BG) it's not. It is said that they use typical background properties.

In the Style chapter, 4.4.9 Properties these categories are listed:
- Mixed properties
- Padding and margin properties
- Background properties
- Border properties
- Outline properties
- Shadow properties
- Pattern properties
- Value properties
- Text properties
- Line properties
- Image properties
- Transition properties
- Scale properties
And in the end says: 
The ”typical background” properties are:
• Background
• Border
• Outline
• Shadow
• Pattern
• Value

Which implies that these are not among ”typical background” properties, right?
- Mixed properties
- Padding and margin properties
- Text properties
- Line properties
- Image properties
- Transition properties
- Scale properties

But then for LV_CHART_PART_BG and LV_CHART_PART_SERIES_BG is mentioned also "text style" and "Padding values" respectively "line style" and "padding values".
So do I understand it right that for LV_CHART_PART_BG can be applied:
• Background
• Border
• Outline
• Shadow
• Pattern
• Value
• + Text
• + Padding and margin
And for LV_CHART_PART_SERIES_BG can be applied:
• Background
• Border
• Outline
• Shadow
• Pattern
• Value
• + Line
• + Padding and margin

Kindly please confirm. Thank you.

**Comment by DaPa** [comment]
Asked also [here](https://forum.lvgl.io/t/charts-clarification-about-styles/2669)

**Comment by kisvegabor** [comment]
Hi,

Yes, that's the case. These parts of the docs are written by me and maybe I'm too involved to write fully clear docs. :sweat_smile: 

Ideas are very welcome about how could we make it clearer.

**Comment by DaPa** [comment]
Thank you for confirmation. If I'll have other issues or ideas certainly I'll come back! :-)
