### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by ali-rostami** [lvgl/docs#136]
Hi
In the **[Style](https://docs.lvgl.io/latest/en/html/overview/style.html)** part of the documentation, not all of the properties has the default value. 
For example, if we see the shadow part, only the **shadow_blend_mode**  has the default value. 
I think it's a good idea to write their default values. I have no idea how to get them easily. If you tell me I can help you with this.

**Comment by kisvegabor** [comment]
Hi,

That's true! 
It's a little bit complicated to find the default values, so I quickly added them.  The docs will be updated in a few minutes.

**Comment by ali-rostami** [comment]
thanks, Gabor
