### ISSUE TITLE
Wrong links on Spinbox documentation

### ISSUE THREAD

**Issue by C47D** [lvgl/docs#141]
When clicking on the Generic Events (and Special Events) hyperlink of the Spinbox documentation
![imagen](https://user-images.githubusercontent.com/11037705/90348890-41b01480-dffd-11ea-9df2-84248019f3e6.png)

I get a 404 page
![imagen](https://user-images.githubusercontent.com/11037705/90348862-16c5c080-dffd-11ea-9596-53072aed2608.png)

The link is `https://docs.lvgl.io/overview/event.html#generic-events`, the correct link seems to be `https://docs.lvgl.io/latest/en/html/overview/event.html#generic-events` and `https://docs.lvgl.io/overview/event.html#special-events` should be replaced with `https://docs.lvgl.io/latest/en/html/overview/event.html#special-events`.

**Comment by kisvegabor** [comment]
It seems it's incorrect on every widgets page. I'm working on it.

**Comment by kisvegabor** [comment]
I've fixed it.

Thanks for pointing it out.
