### ISSUE TITLE
Spelling mistake in banner

### ISSUE THREAD

**Issue by tgillbe** [lvgl/docs#143]
Copies is spelt "Copyes" in the image in the banner:

[https://github.com/lvgl/docs/blob/latest/_static/img/home_banner.jpg](https://github.com/lvgl/docs/blob/latest/_static/img/home_banner.jpg)

**Comment by embeddedt** [comment]
@kisvegabor

**Comment by kisvegabor** [comment]
Ups, sorry for the delay. It's fixed now.
