### ISSUE TITLE
Find broken links automatically? 

### ISSUE THREAD

**Issue by C47D** [lvgl/docs#147]
Hi,

Is there a tool to find broken (404) links on the documentation automatically?

**Comment by kisvegabor** [comment]
I've checked it with an online tool and founds these. Did yo usee others too?
|Error|Target|Link|
-- | -- | --
404 Not Found | https://github.com/lvgl/docs/blob/latest/object-types/index.md | Edit on GitHub
404 Not Found | https://github.com/lvgl/docs/blob/latest/widgets/msdbox.md | Edit on GitHub
404 Not Found | https://github.com/lvgl/docs/tree/latest/locales | locals
404 Not Found | https://github.com/lvgl/docs/blob/release/v7/object-types/index.md | Edit on GitHub
404 Not Found | https://github.com/lvgl/docs/blob/release/v7/widgets/msdbox.md | Edit on GitHub
404 Not Found | https://docs.lvgl.io/overview/style | Style overview
404 Not Found | https://docs.lvgl.io/widgets/cont | layout
404 Not Found | https://docs.lvgl.io/latest/en/html/overview/overview/object | Screens
404 Not Found | https://docs.lvgl.io/porting/indev | associated with the display
404 Not Found | https://docs.lvgl.io/overview/images/ | Image decoder interface
404 Not Found | https://docs.lvgl.io/overview/images | Image decoder
404 Not Found | https://docs.lvgl.io/latest/en/html/_static/fonts/RobotoSlab/roboto-slab.eot | style: @font-face
404 Not Found | https://docs.lvgl.io/widget/cont | Layout
404 Not Found | https://docs.lvgl.io/wisgets/cont | Auto-fit
404 Not Found | https://docs.lvgl.io/overview/image.html | Color formats
404 Not Found | https://docs.lvgl.io/overview/style/ | Margin
404 Not Found | https://docs.lvgl.io/v7/en/html/overview/overview/object | Screens
404 Not Found | https://docs.lvgl.io/v7/en/html/_static/fonts/RobotoSlab/roboto-slab.eot | style: @font-face

**Comment by C47D** [comment]
I will send a PR fixing the links.

**Comment by kisvegabor** [comment]
Thank you Carlos, it would be awesome. 

To make it futureproof the internal links should be relative.  E.g. from the widgets folder: `[Generic events](../overview/event)`

And with anchors, the `.html` neds to be added:
`[Generic events](../overview/event.html#generic-events)`
