### ISSUE TITLE
https://docs.lvgl.io can not be visited from china via VPN

### ISSUE THREAD

**Issue by ideapad2009** [lvgl/docs#152]
Can API PDF doc upload to github? Thank you!

**Comment by embeddedt** [comment]
You should be able to clone the repository and then browse `latest/en/html/index.html` in your browser.

**Comment by embeddedt** [comment]
Or does your VPN also block GitHub cloning?

**Comment by ideapad2009** [comment]
Yes I can  clone the repository. But I want to get the PDF doc.

**Comment by kisvegabor** [comment]
The PDF can be found here. I'll take care to keep it the root folder to make it easier to find.
