### ISSUE TITLE
Generate and update sitemap

### ISSUE THREAD

**Issue by Avamander** [lvgl/docs#159]
The current DuckDuckGo/Bing/Google index state is rather sad, it would be reasonable to autogenerate a sitemap and publish that to make the documentation more accessible.

**Comment by kisvegabor** [comment]
Hi,

Thanks for pointing this out. I've just set up an auto sitemap generation extension. The sitemap will be added on the next rebuild.

**Comment by Avamander** [comment]
Will be eagerly awaiting for a rebuild.

**Comment by kisvegabor** [comment]
We need to fix unrelated issues but we are on it. :) 

BTW, exactly what kind of negative user experience have you faced due to lack the of sitemap?

**Comment by Avamander** [comment]
Being unable to find the correct documentation when using search engines because the pages aren't properly indexed.

**Comment by kisvegabor** [comment]
The sitemap is generated and I've just uploaded it to Google's search index. The magic should happen soon :)
