### ISSUE TITLE
how to change the style of the scrollbar of list widget?

### ISSUE THREAD

**Issue by armembedded** [lvgl/docs#165]
l am using a listview widget in my design and I am going to change the color of the scrollbar?

how can I do that?

**Comment by embeddedt** [comment]
Apply the appropriate styles (probably `bg_color`) to [`LV_LIST_PART_SCRLBAR`](https://docs.lvgl.io/latest/en/html/widgets/list.html#parts-and-styles).

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
