### ISSUE TITLE
How to integrate VNC server to Littlevgl

### ISSUE THREAD

**Issue by stone-tong** [lvgl/docs#172]
How to integrate VNC server to Littlevgl, then user can visit the UI from browser or other VNC client.
Thanks.

**Comment by kisvegabor** [comment]
It depends on what kind of MCU/platform do you use.

If you have a Linux based platform you can use the GTK driver for this purpose: https://github.com/lvgl/lv_drivers/tree/master/gtkdrv

**Comment by stone-tong** [comment]
> It depends on what kind of MCU/platform do you use.
> 
> If you have a Linux based platform you can use the GTK driver for this purpose: https://github.com/lvgl/lv_drivers/tree/master/gtkdrv

Linux based system.

**Comment by kisvegabor** [comment]
On Linux, the GTK driver should do exactly this
