### ISSUE TITLE
Automatic rebuilds

### ISSUE THREAD

**Issue by embeddedt** [lvgl/docs#182]
I have been working for the past few hours on the necessary Actions infrastructure for the documentation to rebuild itself whenever a commit is pushed to the `dev`, `latest,` or `release/v7` branches.

That logic is functioning for the most part now, so I am trying to switch `docs.lvgl.io` to serve pages from the `gh-pages` branch. Unfortunately, GitHub Pages is doing some strange caching and refuses to properly pick up on the CSS from `gh-pages` (it works fine from `master`).

Any ideas why this might be happening? I believe everything has been set up on the automation end correctly; this seems to be a Pages issue.

**Comment by kisvegabor** [comment]
That's awseom. It is so good that you got familiar with the GitHub actions. :slightly_smiling_face: 

> That logic is functioning for the most part now, so I am trying to switch docs.lvgl.io to serve pages from the gh-pages branch. Unfortunately, GitHub Pages is doing some strange caching and refuses to properly pick up on the CSS from gh-pages (it works fine from master).

I don't know what could be the issue. :slightly_frowning_face: I googled for `"gh-pages" css issue` and seems a lot of other people have issues with CSS. [This](https://stackoverflow.com/questions/23434719/middleman-paths-not-working-on-subdirectory/23443761#23443761) and [this](https://github.com/facebook/docusaurus/issues/857) seemed interesting.

Anyway, is there any reason why we need to use `gh-pages`. If `master` works we can use it.

**Comment by embeddedt** [comment]
> Anyway, is there any reason why we need to use `gh-pages`.

I would like to use `gh-pages` as ideally the built content should be in a separate branch from the build scripts themselves.

I suspect it might just take time for the cache to populate, but I was testing it on Saturday around midnight UTC so I didn't want to leave it in this broken state for too long. Do you know if there's any timeframe where the docs can be down for a few hours?

![image](https://user-images.githubusercontent.com/42941056/105732709-bd908000-5efe-11eb-8ab6-ff53b6bb3ad4.png)

**Comment by kisvegabor** [comment]
Most of the LVGL users are from USA and China so the whole day is covered. :slightly_frowning_face: 

I've also checked it and saw that there is a "varnish cache" in the header. 
![image](https://user-images.githubusercontent.com/7599318/105739387-58f21700-5f38-11eb-961e-d4d57a1561ee.png)

github.com also comes via varnish.

Now I see the broken site on PC but if I try from a smartphone and mobilenet it works (from WiFi broken on mobile too).

**Comment by embeddedt** [comment]
You are seeing a broken site even though it is set to `master`? That's strange; it sounds like it might be a GitHub issue then.

**Comment by kisvegabor** [comment]
Still broken here (set back to master ~30 minutes ago)

**Comment by kisvegabor** [comment]
Just restarted my router but didn't help.

Have you ever loaded docs.lvgl.io on your smartphone? If not could you try changing to gh-pages and load the site from mobilenet?

**Comment by embeddedt** [comment]
> If not could you try changing to gh-pages and load the site from mobilenet?

I don't have a data plan on my phone, but I did try loading it on https://www.browserling.com/ on Saturday, and it had the same issue (no CSS, just the raw HTML). Browserling runs a remote browser in the cloud, so I presume it is loading it from a different location.

**Comment by embeddedt** [comment]
It seems to work on Browserling, so the caches going to my PC and your PC must be the ones with the broken requests.

![image](https://user-images.githubusercontent.com/42941056/105741153-fb45d680-5f07-11eb-8a08-d290b5c2b61b.png)

**Comment by kisvegabor** [comment]
Great! So what's next? Try browserling with gh-pages?

**Comment by kisvegabor** [comment]
Ah sorry, you tried it on Saturday...

So what's next? :)

**Comment by embeddedt** [comment]
Would it be possible to host a backup copy of the docs on https://docs2.lvgl.io (or something similar) so we can test things without interrupting developers? I'd like to try flipping it to gh-pages and waiting 24 hours to see if the cache picks up on the change.

**Comment by embeddedt** [comment]
Also, I assume whenever you've built the docs the "normal" way (using `update.py` and pushing to `master`) the change has been reflected almost immediately on docs.lvgl.io, right?

**Comment by kisvegabor** [comment]
Okay, I'm adding a back-up. I'd rather use lvgl.io/docs for the back-up.

> Also, I assume whenever you've built the docs the "normal" way (using update.py and pushing to master) the change has been reflected almost immediately on docs.lvgl.io, right?

Yes, only 1-2 minutes. Waas it slower with gh-pages?

**Comment by embeddedt** [comment]
It quickly switched to the broken HTML, but it did not pick up on the CSS even after I waited 5 minutes. I suspect we are doing something wrong, but I have no idea what it is. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
https://lvgl.io/docs is there.

Now docs.lvgl.io  work for me again. More than 1 hour has passed.

Okay, I'll open a pinned github issue, and write a short announcement on the forum with the backup link.
Let's wait a couple of hours and we will see. 
Do you agree?

**Comment by embeddedt** [comment]
Sounds good. Just to confirm: will you be flipping the branch setting?

**Comment by kisvegabor** [comment]
Yes,
1. GitHub issue
2. Forum announcement
3. Change to gh-pages 

Ok?

**Comment by embeddedt** [comment]
Perfect!

**Comment by kisvegabor** [comment]
Done!

**Comment by kisvegabor** [comment]
All looks good, it became broken here. :smile:

**Comment by embeddedt** [comment]
Same on my end. Hopefully we can get it working, because having instant documentation updates upon a PR merge would be a great feature.

**Comment by kisvegabor** [comment]
Oh yes, it'd be great!

**Comment by kisvegabor** [comment]
I've modified the html in gh-pages and changed "Introduction" in the TOC to "Introduction!" (added exclamation mark).

We will see the HTML gets updated independently from CSS.

**Comment by embeddedt** [comment]
It has updated for me already: https://docs.lvgl.io/latest/en/html/header.html

![image](https://user-images.githubusercontent.com/42941056/105751451-03a40e80-5f14-11eb-8a58-6e48c373124d.png)

This is so confusing!

**Comment by kisvegabor** [comment]
Here now added it to index.html too and measured time. Really only 2 minutes.

Maybe there is a different expiration time on HTML than on CSS.

**Comment by embeddedt** [comment]
Do you think it would be worthwhile to open an issue on the GitHub support forum about this?

**Comment by kisvegabor** [comment]
Yes, I think it's worth to open an issue. 

As a workaround what about adding the script into a `script` branch and deploying it into `master.`

We can safely make experiments now as the docs breakdown is announced.

**Comment by embeddedt** [comment]
That would be awkward, but we may not have a choice. Let's wait a little bit and see if any GitHub staff or community members respond.

https://github.community/t/pages-refuses-to-serve-css-from-one-branch-but-works-on-another/157700

**Comment by kisvegabor** [comment]
Okay, let's give it a few days. 
I suggest restoring the docs to master while waiting and keep the announcements active. Do you agree?

**Comment by embeddedt** [comment]
Personally, I would rather leave it in the broken state (so that others can potentially debug), but I suppose that we want existing docs links to keep working. How about I restore it later this afternoon if no one responds (3PM EST)?

**Comment by kisvegabor** [comment]
You are right. 
But then we should wait more (until tomorrow?) to let people debug it as you suggested.

**Comment by kisvegabor** [comment]
I think it's time to go the the  `script` branch direction. :slightly_frowning_face:

**Comment by embeddedt** [comment]
I think you're right. I was hoping that a staff member would have responded by now, but maybe that forum is not as active as I thought.

Should we restore it to `master` until I have a chance to make the script work on `script`?

**Comment by kisvegabor** [comment]
When will you have time to try it out? If tomorrow or so I think we can wait for it. If it takes several days let's restore it for now.

**Comment by embeddedt** [comment]
It'll be a few days, most likely, so I set the branch back to `master`.

**Comment by kisvegabor** [comment]
Okay, thanks!

**Comment by embeddedt** [comment]
It works! release/v7, dev, and latest are now being deployed automatically - no manual rebuilding necessary. Will test release/v6 soon.

**Comment by embeddedt** [comment]
Change of plan: v6 is just using the most recent precompiled HTML, as the build script didn't behave properly, and I didn't feel it was worth investing more time into given that it's about to be 2 major versions old. We can always hand-edit the HTML if there's anything major which needs adjusting.

**Comment by kisvegabor** [comment]
I've just tested it by removing teh "Download PDF" link from latest aaaaaand it worked like a charm :heart_eyes:  

That's amazing!

I agree to not deal with v6.

**Comment by embeddedt** [comment]
Great! For releases, I think all that needs to be done is merge latest to release/v7 and increment the version number in latest; it’s Essentially the same as the core repo.

**Comment by kisvegabor** [comment]
The docs are updating nicely during the release :) 

The is one issue though that I see on every release. When `lv_examples` is released its CI fails [here](https://github.com/lvgl/lv_examples/blob/master/lv_examples.h#L49).

If I re-run it manually when the emscripten project is updated it runs without errors. Is it normal?

**Comment by embeddedt** [comment]
It seems like normal behavior; I believe to solve this the Emscripten project would have to be updated before you actually tag the release version. Or, we could add a flag so that CI ignores the version check.

**Comment by kisvegabor** [comment]
Actually, it won't be an issue soon once lv_examples and lvgl is merged.

**Comment by embeddedt** [comment]
Are you thinking that 7.10 will be the last 7.x series release?

**Comment by kisvegabor** [comment]
I think we can merge `dev-v8` to `dev` in a few weeks and ask for testing.

So there might be a few releases until that but I can click the re-run button still 2-3 times :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Do you also see that the docs builds are failing after the release? Have I messed up something?

**Comment by embeddedt** [comment]
Syntax error in `conf.py`: https://github.com/lvgl/docs/blob/f30c09771cb29d7dac77e432e7e9ff82b24bffdb/conf.py#L76

I can't fix it right now; will check later if you haven't already fixed it.

**Comment by kisvegabor** [comment]
I've fixed in on [release/v7](https://github.com/lvgl/docs/blob/2ba5a49c64aeda3cdbd5812e664d681afbd1b05a/conf.py#L76) and it was correct on [latest](https://github.com/lvgl/docs/blob/625c54cade04911016b89becf9c41d159d6d1492/conf.py#L76) but still the same error.

**Comment by embeddedt** [comment]
[dev](https://github.com/lvgl/docs/commit/293194cd9eb12a19c9619855fb8d4567cf162f42) also had the problem so I just adjusted it. Let's see what happens now.

**Comment by embeddedt** [comment]
It deployed correctly. I think it's fixed.

**Comment by kisvegabor** [comment]
Hm, somehow the other branches are still not working.

**Comment by embeddedt** [comment]
With the way I have the script setup, a change to one branch rebuilds and redeploys all of them. (They all say "Last updated on Feb 16, 2021." at the bottom.)

However, GitHub will still show the red X on the failing branches until another commit is pushed to them.

**Comment by kisvegabor** [comment]
Oh, I see! All good then. LVGL version is really update on the top left of the webpage.

It seems the rebuild works well and this issue can be closed.

**Comment by embeddedt** [comment]
Great!
