### ISSUE TITLE
misspellings in document

### ISSUE THREAD

**Issue by mhsoftware100** [lvgl/docs#191]
There are two misspellings in the  documentation
![bug](https://user-images.githubusercontent.com/77447852/107879838-80f9e800-6ef0-11eb-963e-1777044a7f7b.jpg)

**Comment by kisvegabor** [comment]
Thanks! Could you help us by sending a PR for this? Just click the edit on GitHub button on the top of the page and send a PR directly from GitHub.

**Comment by kisvegabor** [comment]
Fixed here: eee14aa
