### ISSUE TITLE
We do need a up-to-date PDF doc

### ISSUE THREAD

**Issue by Lawrence-Link** [lvgl/docs#200]
We do need an up-to-date PDF doc for v7, but why was it pulled down? maybe it's too hard to keep up with new commits?

**Comment by embeddedt** [comment]
Documentation gets rebuilt automatically so keeping up with commits isn't an issue.

The reason we disabled PDF builds is that it was hanging for an inexplicable reason, and this was delaying the update for the HTML documentation.

I am currently in the process of revamping the documentation scripts for v8 so I will look at re-enabling PDFs again.

**Comment by Lawrence-Link** [comment]
good to hear that :P

**Comment by embeddedt** [comment]
As a workaround for now, if having a copy of the documentation that can be accessed offline is the issue, you can take a standard GitHub ZIP download of this repository's `master` branch. That will give you the HTML files which you can then open in your browser even if offline.

**Comment by embeddedt** [comment]
(cc @kisvegabor)

After quite a bit of debugging I finally found the issue for Latex builds. The list of colors in [this file](https://github.com/lvgl/lvgl/blob/5e25cec25da5de79394c99bbb32f9bae83d31b5b/docs/overview/display.md#built-in-colors) uses external images which were apparently failing to download on Sphinx. However, it seemed to have an absurdly high retry timeout which caused it to spend several minutes on one of the images. Multiply this by the number of images and we get a 1 hour build. :laughing: 

These color macros don't exist in v8, so I'm just going to remove them from the docs for now. We can add back more relevant documentation for the palette system later.

PDF builds for v8 should be available shortly; I'll be re-enabling them tonight (barring any further issues).

**Comment by kisvegabor** [comment]
@embeddedt 
Amazing! :tada: :tada: :tada: 

I wonder if there is a way to somehow include a screenshot of the widget examples in the PDF. Not critical, just asking.

**Comment by embeddedt** [comment]
It's a bit difficult to do now because we don't have a screenshot in-tree anymore, so it would have to be generated at build time. That could be done, but I think it would slow down the build quite a bit. I'll think about it and see if I can come up with anything.

**Comment by Lawrence-Link** [comment]
@embeddedt thanks so much!
well this is really helpful

**Comment by embeddedt** [comment]
@Lawrence-Link Glad it helped!

In case it's useful for you or anyone else, here is a v7 PDF with the same problematic section removed:

[LVGL.pdf](https://github.com/lvgl/docs/files/6442740/LVGL.pdf)
